final int CHARACTER_SPACE = 32;
final int CHARACTER_RANGE_LOW = 32;
final int MAX_UNICODE_POINT = 173782;

final int NUMBER_RANGE_LOW = 48;
final int NUMBER_RANGE_HIGH = 57;

final int LOWER_CASE_RANGE_LOW = 97;
final int LOWER_CASE_RANGE_HIGH = 122;

final int UPPER_CASE_RANGE_LOW = 65;
final int UPPER_CASE_RANGE_HIGH = 90;

final int PUNCTUATION_RANGE_ONE_LOW = 33;
final int PUNCTUATION_RANGE_ONE_HIGH = 47;

final int PUNCTUATION_RANGE_TWO_LOW = 58;
final int PUNCTUATION_RANGE_TWO_HIGH = 64;

final int PUNCTUATION_RANGE_THREE_LOW = 91;
final int PUNCTUATION_RANGE_THREE_HIGH = 96;

final int PUNCTUATION_RANGE_FOUR_LOW = 123;
final int PUNCTUATION_RANGE_FOUR_HIGH = 126;
